version: '3'
services:
  winery:
    image: opentosca/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      CONTAINER_HOSTNAME: ${PUBLIC_HOSTNAME}
      EDMM_TRANSFORMATION_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_FEATURE_EDMM_MODELING: 'true'
    volumes:
      - ./modeling-repository:/var/opentosca/repository
    ports:
      - '8080:8080'
  transformation-framework:
    image: ustedmm/transformation-framework:latest
    ports:
      - '5000:5000'
