version: '3'
services:
  tosca-lightning:
    build:
      context: .
    image: ustedmm/tosca-lightning:latest
    environment:
      WINERY_HOSTNAME: winery
      WINERY_PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
      TRANSFORMATION_HOSTNAME: transformation-framework
      TRANSFORMATION_PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
    ports:
      - '9000:8080'
  winery:
    image: opentosca/winery:latest
    environment:
      WINERY_HOSTNAME: ${PUBLIC_HOSTNAME}
      WORKFLOWMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      TOPOLOGYMODELER_HOSTNAME: ${PUBLIC_HOSTNAME}
      EDMM_TRANSFORMATION_HOSTNAME: ${PUBLIC_HOSTNAME}
      WINERY_FEATURE_EDMM_MODELING: 'true'
    volumes:
      - ./modeling-repository:/var/repository
    ports:
      - '8080:8080'
  transformation-framework:
    image: ustedmm/transformation-framework:latest
    volumes:
      - ./modeling-repository:/var/repository
    ports:
      - '5000:5000'
